name: Salescope
channels:
  - defaults
  - conda-forge
dependencies:
  - altair=5.5.0
  - click=8.2.1
  - click-default-group=1.2.2
  - conda-lock=3.0.4
  - dash=2.14.2
  - ipykernel=6.29.5
  - ipywidgets=8.1.5
  - jupyterlab=4.0.11
  - make=4.2.1
  - matplotlib=3.10.0
  - numpy=2.3.1
  - pandas=2.3.1
  - pandoc=3.6.3
  - pandocfilters=1.5.0
  - pip=25.3
  - plotly=6.0.1
  - pydantic=2.11.7
  - pytest=8.4.1
  - python=3.12.12
  - quarto=1.8.27
  - requests=2.32.4
  - shiny=1.4.0
  - tabulate=0.9.0
  - tinycss2=1.4.0
  - urllib3=2.5.0
  - vegafusion=2.0.2
  - vegafusion-jupyter=1.6.9
  - wheel=0.45.1
  - scipy=1.16.0
  - ridgeplot=0.5.0
  - seaborn=0.13.2
  - shinywidgets=0.7.1
  - anywidget=0.9.18
